# Generated by Django 4.0.3 on 2022-03-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_issue', models.CharField(default=None, max_length=50)),
                ('date_issue', models.DateField()),
            ],
            options={
                'db_table': 'Book_Issued',
            },
        ),
    ]
