# Generated by Django 4.0.3 on 2022-03-04 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_book_issue'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book_issue',
            table='Book_Issued',
        ),
    ]
