# Generated by Django 3.2.4 on 2022-02-01 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
