# Generated by Django 4.0.3 on 2022-03-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_book_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_issue',
            name='date_issue',
            field=models.IntegerField(),
        ),
    ]
