# Generated by Django 4.0.3 on 2022-03-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_book_issue_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_issue',
            name='book_issue',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
