# Generated by Django 3.2.4 on 2022-02-02 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_user_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
