# Generated by Django 3.2.4 on 2022-02-02 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_users_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='Users_info',
        ),
    ]
