# Generated by Django 3.2.4 on 2022-02-02 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_user_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
