# Generated by Django 4.0.2 on 2022-02-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0007_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_uploader', models.CharField(max_length=50)),
                ('book_name', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('number_of_pages', models.IntegerField(max_length=10)),
                ('brief_description', models.CharField(max_length=150)),
            ],
        ),
    ]
