# Generated by Django 4.0.2 on 2022-02-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_register',
            name='number_of_pages',
            field=models.IntegerField(),
        ),
    ]
