# Generated by Django 4.0.2 on 2022-02-02 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_book_register_number_of_pages'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book_register',
            table='Registered_books',
        ),
    ]
