# Generated by Django 4.0.2 on 2022-02-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_book_register_rating_book_register_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_register',
            name='review',
            field=models.CharField(max_length=120),
        ),
    ]
