# Generated by Django 4.0.2 on 2022-02-03 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_book_register_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_register',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='book_register',
            name='review',
        ),
    ]
